# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77664e1bce832f6ec764850e7e38c216ce6c6824f94a73211a38638744338f35b988d690103a2aa47a7a2a22255e77a17b6dfb03500f158c8283f2dc9bfc36cd

test:
  secret_key_base: 59e16887e6a79a428cd0317ede219616e82d4953c5f5665c3f7ea3d1008a307b9d6b64d93e3d7c166e3ec110ad4fdeb8a3dda3bc0f6914afb1095faaade50881

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
